accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path('signup/', views.SignUp, name="sing_up"),
    path('profile/', views.profile, name="profile"),
    path('profile/edit', views.profile_edit, name="profile_edit")
]

job/urls.py
from django.urls import path
from . import views
app_name = "job"
urlpatterns = [
    path('', views.job_list, name="job_list"),
    path('add/', views.add_job, name="add_job"),
    path('<str:slug>/', views.job_detail, name="job_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)
    city = models.ForeignKey('City', null=True, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to="profile/")

    def __str__(self):
        return str(self.user)

class City(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

@receiver(post_save, sender = User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
from django.contrib.auth.models import User
import re
# importing slugify from django
from django.utils.text import slugify
# Create your models here.
def image_upload(instance, file_name):

    extension_name = file_name.split(".")[1]
    return f"jobs/{instance.id}.{extension_name}"
class Job(models.Model):
    JOB_NUTURE_CHOICES = [
        ('Full Time', 'Full Time'),
        ('Part Time', 'Part Time'),
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # location
    job_nature = models.CharField(max_length=15, choices=JOB_NUTURE_CHOICES)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload) 
    slug = models.SlugField(blank=True, null=True)
    same_slugs = models.IntegerField(default=0)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        same_slugs_data = list(Job.objects.all().filter(title = self.title))
        same_slugs_len = len(same_slugs_data)
        if  same_slugs_len >= 1:
            self.same_slugs = same_slugs_data[same_slugs_len - 1].same_slugs + 1
            self.slug += str(self.same_slugs)
        super(Job, self).save(*args, **kwargs)
    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class Apply(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    coverletter = models.TextField(max_length=500)
    created_at = models.DateField(auto_now=True)
    def __str__(self):
        return self.name

accounts/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields= ["username", "email", "password1", "password2"]

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]
    

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["phone_number", "city", "image"]

job/forms.py
from django import forms
from .models import Apply, Job

class ApplyForm(forms.ModelForm):
    class Meta:
        model = Apply
        fields = "__all__"
        exclude = ["job"]
class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = "__all__"
        exclude = ["owner","slug", "same_slugs"]

accounts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import SignUpForm, UserForm, ProfileForm
from .models import Profile
from django.contrib.auth import authenticate, login

# Create your views here.

def SignUp(request):
    
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('jobs:job_list'))
    else:
        form = SignUpForm()
    context = {
        'form': form
    }
    return render(request, "registration/signup.html", context)


def profile(request):
    user_profile = Profile.objects.get(user=request.user)
    context = {
        "profile": user_profile
    }
    return render(request, "accounts/profile.html", context)


def profile_edit(request):
    user_profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user_profile)

        if user_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(reverse("accounts:profile"))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=user_profile)
    context = {
        "user_form": user_form,
        "profile_form": profile_form
    }
    return render(request, "accounts/profile_edit.html", context)

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from .models import Job
from .forms import ApplyForm, AddJobForm
from .filters import JobFilter

# Create your views here.

def job_list(request):
    filter = JobFilter(request.GET, queryset=Job.objects.all())
    paginator = Paginator(filter.qs, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'jobs': page_obj,
        'filter': filter.form
    }
    return render(request, 'job/job_list.html', context)

def job_detail(request, slug):
    job_detail = Job.objects.get(slug=slug)

    if request.method == "POST":
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            current_apply = form.save(commit=False)
            current_apply.job = job_detail
            current_apply.save()

    form = ApplyForm()

    context = {
    'job': job_detail, 
    'form': form
    }
    return render(request, 'job/job_detail.html', context)  

@login_required
def add_job(request):
    
    if request.method == "POST":
        form = AddJobForm(request.POST, request.FILES)
        if form.is_valid():
            current_job = form.save(commit=False)
            current_job.owner = request.user
            current_job.save()
            return redirect(reverse('jobs:job_list'))
    form = AddJobForm()
    context = {
        'form': form
    }
    return render(request, 'job/add_job.html', context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %} {% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>user details</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>
                                name:
                                <span>{{profile.user.username}}</span>
                            </li>
                            <li>
                                email: <span>{{profile.user.email}}</span>
                            </li>
                            <li>phone: <span>{{profile.phone_number}}</span></li>
                            <li>address: <span>{{profile.city}}</span></li>
                        </ul>
                    </div>
                    <div class="edit p-5"><a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-100">edit profile</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %} {% load bootstrap5 %} {% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>edit profile</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <div class="apply_job_form white-bg">
                    <h4>edit profile</h4>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form user_form %}
                        {% bootstrap_form profile_form %}
                        {% buttons %}
                        <div class="submit_btn">
                            <button class="boxed-btn3 w-100" type="submit">
                                save
                            </button>
                        </div>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

job/templates/job/add_job.html
{% extends 'base.html' %} {% load bootstrap5 %} {% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>add job</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                {% comment %} <div class="job_details_header">
                    <div
                        class="single_jobs white-bg d-flex justify-content-between"
                    >
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="img/svg_icon/1.svg" alt="" />
                            </div>
                            <div class="jobs_conetent">
                                <a href="#"><h4>{{job.title}}</h4></a>
                                <div
                                    class="links_locat d-flex align-items-center"
                                >
                                    <div class="location">
                                        <p>
                                            <i class="fa fa-map-marker"></i>
                                            California, USA
                                        </p>
                                    </div>
                                    <div class="location">
                                        <p>
                                            <i class="fa fa-clock-o"></i>
                                            {{job.job_nature}}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#">
                                    <i class="ti-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        <h4>{{job.title}}</h4>
                        <p>{{job.description}}</p>
                    </div>
                </div> {% endcomment %}
                <div class="apply_job_form white-bg">
                    <h4>add new job</h4>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                        <div class="submit_btn">
                            <button class="boxed-btn3 w-100" type="submit">
                                Apply Now
                            </button>
                        </div>
                        {% endbuttons %}
                        {% comment %}

                        {% endcomment %} {% comment %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input_field">
                                    <input
                                        type="text"
                                        name="name"
                                        placeholder="Your name"
                                    />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="input_field">
                                    <input
                                        type="text"
                                        placeholder="Email"
                                        name="email"
                                    />
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="input_field">
                                    <input
                                        type="text"
                                        name="website"
                                        placeholder="Website/Portfolio link"
                                    />
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button
                                            type="button"
                                            id="inputGroupFileAddon03"
                                        >
                                            <i
                                                class="fa fa-cloud-upload"
                                                aria-hidden="true"
                                            ></i>
                                        </button>
                                    </div>
                                    <div class="custom-file">
                                        <input
                                            type="file"
                                            class="custom-file-input"
                                            id="inputGroupFile03"
                                            aria-describedby="inputGroupFileAddon03"
                                            name="file"
                                        />
                                        <label
                                            class="custom-file-label"
                                            for="inputGroupFile03"
                                            >Upload CV</label
                                        >
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="input_field">
                                    <textarea
                                        name="message"
                                        id=""
                                        cols="30"
                                        rows="10"
                                        placeholder="Coverletter"
                                    ></textarea>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="submit_btn">
                                    <button
                                        class="boxed-btn3 w-100"
                                        type="submit"
                                    >
                                        Apply Now
                                    </button>
                                </div>
                            </div>
                        </div>
                        {% endcomment %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

job/templates/job/job_list.html
{% extends 'base.html' %} {% load bootstrap5 %} {% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{jobs.count}}+ Jobs Available</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form>
                            {% bootstrap_form filter %}
                                <button class="boxed-btn3 w-100 mt-3" type="submit">
                                    search
                                </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Job Listing</h4>
                            </div>
                            <div class="col-md-6">
                                <div
                                    class="serch_cat d-flex justify-content-end"
                                >
                                    <select>
                                        <option data-display="Most Recent">
                                            Most Recent
                                        </option>
                                        <option value="1">Marketer</option>
                                        <option value="2">Wordpress</option>
                                        <option value="4">Designer</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0">
                    <div class="row">
                        {% for job in jobs %}
                        <div class="col-lg-12 col-md-12">
                            <div
                                class="single_jobs white-bg d-flex justify-content-between"
                            >
                                <div
                                    class="jobs_left d-flex align-items-center"
                                >
                                    <div class="thumb">
                                        <!-- <img src="{{job.image.url}}" alt="" /> -->
                                    </div>
                                    <div class="jobs_conetent">
                                        <a
                                            href="{% url 'jobs:job_detail' job.slug %}"
                                            ><h4>{{job.title}}</h4></a
                                        >
                                        <div
                                            class="links_locat d-flex align-items-center"
                                        >
                                            <div class="location">
                                                <p>
                                                    <i
                                                        class="fa fa-map-marker"
                                                    ></i>
                                                    California, USA
                                                </p>
                                            </div>
                                            <div class="location">
                                                <p>
                                                    <i
                                                        class="fa fa-clock-o"
                                                    ></i>
                                                    {{job.job_nature}}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="heart_mark" href="#">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                        <a
                                            href="{% url 'jobs:job_detail' job.slug %}"
                                            class="boxed-btn3"
                                            >Apply Now</a
                                        >
                                    </div>
                                    <div class="date">
                                        <p>
                                            Date line:
                                            {{job.published_at|date:'d M o'}}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% if jobs.has_other_pages %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="pagination_wrap">
                                <ul>
                                    {% if jobs.has_previous %}
                                    <li>
                                        <a
                                            href="?page={{jobs.previous_page_number}}"
                                        >
                                            <i class="ti-angle-left"></i>
                                        </a>
                                    </li>
                                    {% endif %}
                                    {% for page in jobs.paginator.page_range %}
                                    <li>
                                        <a href="?page={{page}}"
                                            ><span>{{page}}</span></a
                                        >
                                    </li>
                                    {% endfor %}
                                    {% if jobs.has_next %}
                                    <li>
                                        <a 
                                            href="?page={{jobs.next_page_number}}"
                                        >
                                            <i class="ti-angle-right"></i>
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_end  -->
{% endblock %}